--流氓爬虫
local scanner_list = { " injection",
    "8484 boston project",
    "; widows",
    "a href=",
    "adsarobot",
    "advanced email extractor",
    "agdm79@mail.ru",
    "amiga-aweb/3.4",
    "athens",
    "atomic_email_hunter",
    "atspider",
    "attache",
    "autoemailspider",
    "backdoor",
    "black hole",
    "botversion",
    "butch__2.1.1",
    "bwh3_user_agent",
    "cheesebot",
    "cherrypicker",
    "china local browse 2.",
    "chinaclaw",
    "compatible ; msie",
    "compatible ;.",
    "compatible-",
    "concealed defense",
    "contactbot/",
    "contentsmartz",
    "converacrawler",
    "copyguard",
    "copyrightcheck",
    "core-project/1",
    "crescent internet toolpak",
    "datacha0s",
    "digimarc webreader",
    "digout4uagent",
    "dts agent",
    "ecollector",
    "educate search vxb",
    "eirgrabber",
    "email",
    "email extractor",
    "emailcollect",
    "emailharvest",
    "emailmagnet",
    "emailreaper",
    "emailsiphon",
    "emailwolf",
    "eo browse",
    "extractorpro",
    "fantombrowser",
    "fastlwspider",
    "faxobot",
    "fiddler",
    "floodgate",
    "foobar/",
    "franklin locator",
    "full web bot",
    "gameBoy, powered by nintendo",
    "gecko/2525",
    "grub crawler",
    "grub-client",
    "hanzoweb",
    "hhjhj@yahoo",
    "hl_ftien_spider",
    "indy library",
    "internet exploiter sux",
    "internet ninja",
    "internet-exprorer",
    "isc systems irc search 2.1",
    "jakarta",
    "kenjin spider",
    "larbin@unspecified",
    "mailto:craftbot@yahoo.com",
    "microsoft internet explorer/5.0",
    "microsoft url",
    "microsoft url control",
    "missigua",
    "morfeus fucking scanner",
    "morzilla",
    "mosiac 1",
    "mozilla/3.mozilla/2.01",
    "murzillo compatible",
    "nameofagent",
    "nessus",
    "neuralbot/0.2",
    "newt activeX; win32",
    "nikto",
    "no browser",
    "nokia-waptoolkit",
    "packrat",
    "panscient.com",
    "pcbrowser",
    "pe 1.4",
    "pleasecrawl/1.",
    "pmafind",
    "poe-component-client",
    "production bot",
    "program shareware 1.0.",
    "prowebwalker",
    "psurf",
    "psycheclone",
    "rsync",
    "s.t.a.l.k.e.r.",
    "safexplorer tl",
    "searchbot admin@google",
    "security scan",
    "shai",
    "sitesnagger",
    "stress test",
    "surveybot",
    "takeout",
    "teleport pro",
    "telesoft",
    "this is an exploit",
    "toata dragostea mea pentru diavola",
    "turing machine",
    "under the rainbow 2.",
    "user-Agent",
    "user-agent:",
    "vadixbot",
    "via",
    "voideye",
    "w3mir",
    "web by mail",
    "web downloader",
    "webaltbot",
    "webbandit",
    "webemailextrac",
    "webemailextract",
    "webmole",
    "webroot",
    "webster pro",
    "webvulnscan",
    "wells search ii",
    "wep Search 00",
    "windows-update-agent",
    "wisebot",
    "wisenutbot",
    "wordpress hash grabber",
    "wordpress/4.01",
    "www.weblogs.com",
    "xmlrpc exploit",
    "zeus", }


local ua = ngx.var.http_user_agent;
if ua then
    ua = string.lower(ua);
    for _, scanner in pairs(scanner_list) do
        if string.find(ua, scanner, 1, true) then
            return true;
        end
    end
end
return false
