--扫描工具爬虫
local scanner_list = { "(hydra)",
    ".nasl",
    "80legs",
    "absinthe",
    "ache/",
    "aiohttp/",
    "antsword",
    "appscan",
    "arachni",
    "arachni/",
    "autogetcontent",
    "bilbo",
    "black widow",
    "blackwidow",
    "brutus",
    "bsqlbf",
    "burpcollaborator",
    "censysinspect",
    "cgichk",
    "colly -",
    "crawler4j",
    "crowdstrike",
    "dav.pm/v",
    "dbappsecurity",
    "dirbuster",
    "gobuster",
    "grabber",
    "grendel-scan",
    "havij",
    "headlesschrome",
    "hp asc",
    "http banner detection",
    "httpx",
    "hydra",
    "jaascois",
    "libwww-perl",
    "masscan",
    "metis",
    "n-stealth",
    "nessus",
    "netsparker",
    "nikto",
    "nmap",
    "nmap nse",
    "nsauditor",
    "nuclei",
    "nutchcvs/",
    "openvas",
    "pangolin",
    "paros",
    "pmafind",
    "pyspider/",
    "python-",
    "python-httplib2",
    "python-urllib",
    "qqgamehall",
    "qualys",
    "rsas",
    "s.t.a.l.k.e.r.",
    "scrapy/",
    "sql power injector",
    "sqlmap",
    "sqlninja",
    "unirest-java/",
    "vega/",
    "w3af",
    "wappalyzer",
    "webinspect",
    "webreaver",
    "webtrends security analyzer",
    "wfuzz",
    "winhttp.winhttprequest" }


local ua = ngx.var.http_user_agent;
if ua then
    ua = string.lower(ua);
    for _, scanner in pairs(scanner_list) do
        if string.find(ua, scanner, 1, true) then
            return true;
        end
    end
end
return false
