#!/bin/bash -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$DIR/.common.sh"


chmod -R 777 ../

# Ensure docker-compose exists
if hash docker 2>/dev/null && docker compose --version >/dev/null 2>&1; then
	cd "${DIR}/.."
	echo -e "${BLUE}❯ ${CYAN}Starting Dev Stack ...${RESET}"

	docker compose up restart 

	echo ""
	echo -e "${CYAN}Admin UI:     http://127.0.0.1:3081${RESET}"
	echo -e "${CYAN}Nginx:        http://127.0.0.1:3080${RESET}"
	echo -e "${CYAN}Swagger Doc:  http://127.0.0.1:3001${RESET}"
	echo ""

	if [ "$1" == "-f" ]; then
		echo -e "${BLUE}❯ ${YELLOW}Following Backend Container:${RESET}"
		docker logs -f npm_core
	else
		echo -e "${YELLOW}Hint:${RESET} You can follow the output of some of the containers with:"
		echo "  docker logs -f npm_core"
	fi
else
	echo -e "${RED}❯ docker compose command is not available${RESET}"
fi
